### ISSUE TITLE
Создать отдельный проект, являющийся общим для всего приложения

### ISSUE THREAD

**Issue by AlexBimlnk** [AlexBimlnk/QuickMaths#26]
Обсуждали что, например, структура данных должна уметь помещать в себе математические выражения в целом. А значить и функциональная библиотека должна обращаться за наполнением к структуре данных. И библиотека матриц должна посылать запросе структуре данных. В будущем модуль отвечающий за анализ (одз, производные и пр) также должно обрабатывать именно структуру данных. Так что имеет смысл вынести структуру данных, а заодно и общие абстракции (интерфейсы) в общий проект QuickMaths.General. Кстати говоря, видимо арифметическое ядро также должно быть в этом проекте, т.к оно очень тесно взаимодействует с деревом и в целом, наверное, выполнение арифметики - базовая вещь, в отличии, например, от анализа.

**Comment by wi1sp** [comment]
done
